# Generated by Django 5.1.6 on 2025-05-07 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDisciplinaTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flutelink.disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Breaker',
            fields=[
                ('usuario_disciplina_tipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flutelink.usuariodisciplinatipo')),
                ('nivel', models.CharField(max_length=50)),
                ('crew', models.CharField(max_length=100)),
                ('estilo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cantante',
            fields=[
                ('usuario_disciplina_tipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flutelink.usuariodisciplinatipo')),
                ('genero', models.CharField(max_length=100)),
                ('experiencia', models.IntegerField()),
                ('estilo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Graftero',
            fields=[
                ('usuario_disciplina_tipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flutelink.usuariodisciplinatipo')),
                ('estilo', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumentista',
            fields=[
                ('usuario_disciplina_tipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flutelink.usuariodisciplinatipo')),
                ('instrumento', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('experiencia', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('usuario_disciplina_tipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flutelink.usuariodisciplinatipo')),
                ('programa', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('experiencia', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usuariodisciplinatipo',
            name='usuario_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flutelink.usuariodisciplina'),
        ),
    ]
