# Generated by Django 5.1.6 on 2025-05-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flutelink', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graftero',
            new_name='Grafitero',
        ),
    ]
