# Generated by Django 5.1.6 on 2025-05-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutelink', '0002_rename_graftero_grafitero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantante',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='cantante',
            name='busca',
            field=models.CharField(choices=[('cantante', 'Cantante'), ('breaker', 'Breaker'), ('grafitero', 'Grafitero'), ('instrumentista', 'Instrumentista'), ('productor', 'Productor')], default='cantante', max_length=100),
        ),
        migrations.AddField(
            model_name='cantante',
            name='ubicacion_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cantante',
            name='ubicacion_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
