# Generated by Django 5.1.6 on 2025-05-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutelink', '0003_remove_cantante_ubicacion_cantante_busca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantante',
            name='estilo',
        ),
        migrations.AlterField(
            model_name='cantante',
            name='busca',
            field=models.TextField(blank=True),
        ),
    ]
