# Generated by Django 5.1.6 on 2025-05-14 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutelink', '0004_remove_cantante_estilo_alter_cantante_busca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bailarin',
            fields=[
                ('usuario_disciplina_tipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flutelink.usuariodisciplinatipo')),
                ('experiencia', models.CharField(max_length=50)),
                ('crew', models.CharField(max_length=100)),
                ('estilo', models.CharField(max_length=100)),
                ('ubicacion_lat', models.FloatField(blank=True, null=True)),
                ('ubicacion_lng', models.FloatField(blank=True, null=True)),
                ('busca', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='grafitero',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='instrumentista',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='productor',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='grafitero',
            name='busca',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grafitero',
            name='ubicacion_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grafitero',
            name='ubicacion_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentista',
            name='busca',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instrumentista',
            name='ubicacion_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentista',
            name='ubicacion_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productor',
            name='busca',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productor',
            name='ubicacion_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productor',
            name='ubicacion_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Breaker',
        ),
    ]
