# Generated by Django 5.1.6 on 2025-05-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutelink', '0005_bailarin_remove_grafitero_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailarin',
            name='experiencia',
            field=models.IntegerField(max_length=50),
        ),
    ]
