# Generated by Django 5.1.6 on 2025-05-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutelink', '0006_alter_bailarin_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailarin',
            name='experiencia',
            field=models.IntegerField(),
        ),
    ]
